### list of apps
GET http://{{host}}/api/apps
Accept: application/json

### update existing app
POST http://{{host}}/api/apps/app1
Content-Type: application/json

{
  "id": "app1",
  "name": "Josh App",
  "short_name": "josh"
}

### create new app
POST http://{{host}}/api/apps
Content-Type: application/json

{
  "name": "Josh Stage App",
  "short_name": "jstg"
}

