### run for new user
POST https://{{host}}/api/run
Content-Type: application/json

{
  "app_id": "Ok-cUE-XSGUqyRWiqwKti",
  "project_id": "V1NauWW7Qs73MR5J6X0ZF",
  "user_id": "1234",
  "context": {
    "app_version": "4.9.16",
    "new_user": true
  }
}

### run for new user
POST https://abof.myjosh.in/api/run
Content-Type: application/json

{
  "app_id": "Ok-cUE-XSGUqyRWiqwKti",
  "project_id": "V1NauWW7Qs73MR5J6X0ZF",
  "user_id": "1234",
  "context": {
    "app_version": "4.9.16",
    "new_user": true
  }
}

### run for relaunch
POST http://{{host}}/api/run
Content-Type: application/json

{
  "app_id": "Ok-cUE-XSGUqyRWiqwKti",
  "project_id": "V1NauWW7Qs73MR5J6X0ZF",
  "user_id": "12345",
  "context": {
    "app_version": "4.7.5",
    "new_user": false
  }
}